apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: base
  name: web-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base
  template:
    metadata:
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        app: base
    spec:
      containers:
        - image: ayushkumawat/metrics:v1
          name: web-base
          ports:
            - containerPort: 80
